# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='active_reporting_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='e.g. 2024 — used as the default year in UI filters', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.CharField(blank=True, choices=[('MANUFACTURING', 'Manufacturing'), ('ENERGY', 'Energy & Utilities'), ('FINANCIAL', 'Financial Services'), ('TECHNOLOGY', 'Technology'), ('RETAIL', 'Retail & Consumer'), ('TRANSPORT', 'Transport & Logistics'), ('HEALTHCARE', 'Healthcare'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default='default-tenant', help_text="URL-safe identifier, e.g. 'acme-corp'", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='org_tenant',
        ),
        migrations.CreateModel(
            name='ESGUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor (read-only)')], default='ANALYST', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants Django admin site access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='Null only for Django superusers not tied to a tenant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'org_esg_user',
                'indexes': [models.Index(fields=['tenant', 'role'], name='idx_user_tenant_role')],
            },
        ),
    ]
