# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestedRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Unmodified source data — the legal and compliance anchor')),
                ('source_row_index', models.PositiveIntegerField(blank=True, help_text='Row / line number in the original file for debugging', null=True)),
                ('checksum', models.CharField(help_text='SHA-256 hex digest of raw_payload for duplicate detection', max_length=64)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'esg_raw_row',
                'ordering': ['batch', 'source_row_index'],
            },
        ),
        migrations.RemoveField(
            model_name='rawingesteddata',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='filename',
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='external_ref',
            field=models.CharField(blank=True, help_text='Original filename, API batch ID, or storage key for re-ingestion traceability', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='name',
            field=models.CharField(default='Unnamed Batch', help_text="Human label, e.g. 'SAP Plant 42 – Oct 2024'", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='reporting_year',
            field=models.PositiveSmallIntegerField(default=2024, help_text='Calendar or fiscal year this batch covers, e.g. 2024'),
            preserve_default=False,
        ),
    ]
