# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_normalisedemissionrecord_locked_by_and_more'),
        ('ingestion', '0002_rawingestedrow_remove_rawingesteddata_batch_and_more'),
        ('tenants', '0002_tenant_active_reporting_year_tenant_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='error_summary',
            field=models.JSONField(blank=True, help_text='Pipeline errors captured during ingestion, keyed by stage', null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP (Fuel & Procurement)'), ('UTILITY', 'Utility (Electricity Bills)'), ('TRAVEL', 'Corporate Travel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['tenant', 'source_type', 'reporting_year'], name='idx_batch_tenant_src_year'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['status'], name='idx_batch_status'),
        ),
        migrations.AlterModelTable(
            name='uploadbatch',
            table='esg_upload_batch',
        ),
        migrations.AddField(
            model_name='rawingestedrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_rows', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='rawingestedrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_rows', to='tenants.tenant'),
        ),
        migrations.DeleteModel(
            name='RawIngestedData',
        ),
        migrations.AddIndex(
            model_name='rawingestedrow',
            index=models.Index(fields=['tenant', 'batch'], name='idx_raw_tenant_batch'),
        ),
        migrations.AddIndex(
            model_name='rawingestedrow',
            index=models.Index(fields=['checksum'], name='idx_raw_checksum'),
        ),
        migrations.AddConstraint(
            model_name='rawingestedrow',
            constraint=models.UniqueConstraint(fields=('batch', 'checksum'), name='uq_raw_row_batch_checksum'),
        ),
    ]
