# Generated by Django 6.0.5 on 2026-05-29 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Record Created'), ('edit', 'Record Edited'), ('approve', 'Record Approved (Locked)'), ('flag', 'Record Flagged for Review'), ('unlock', 'Record Unlocked')], max_length=20)),
                ('performed_by', models.CharField(help_text='Username or email of the actor', max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, help_text='State of record before change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='State of record after change', null=True)),
                ('comment', models.TextField(blank=True, help_text='Rationale for the review action', null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
