# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text="Model name of the changed object, e.g. 'NormalisedEmissionRecord'", max_length=100)),
                ('object_id', models.UUIDField(help_text='Primary key of the changed object')),
                ('action', models.CharField(help_text='e.g. STATUS_CHANGE, FIELD_EDIT, LOCK, REJECT, INGEST', max_length=50)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('field_name', models.CharField(blank=True, help_text='Which field changed; empty for multi-field actions', max_length=100)),
                ('before_value', models.JSONField(blank=True, help_text='State before the change (typed as JSON to decouple from model schema)', null=True)),
                ('after_value', models.JSONField(blank=True, help_text='State after the change', null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'esg_audit_entry',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_resolved', models.BooleanField(default=False, help_text='True when the comment thread has been addressed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esg_review_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='record',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='tenant',
        ),
    ]
