# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_normalisedemissionrecord_locked_by_and_more'),
        ('reviews', '0002_auditentry_reviewcomment_remove_audittrail_record_and_more'),
        ('tenants', '0002_tenant_active_reporting_year_tenant_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emissions.normalisedemissionrecord'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_comments', to='tenants.tenant'),
        ),
        migrations.DeleteModel(
            name='AuditTrail',
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['object_type', 'object_id'], name='idx_audit_object'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['tenant', 'performed_at'], name='idx_audit_tenant_time'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['performed_by'], name='idx_audit_actor'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['record', 'is_resolved'], name='idx_comment_record_resolved'),
        ),
    ]
