# Generated by Django 6.0.5 on 2026-05-29 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility', models.CharField(help_text='Resolved user-friendly facility name', max_length=255)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct Emissions'), ('Scope 2', 'Scope 2 - Indirect Electricity'), ('Scope 3', 'Scope 3 - Value Chain / Travel / Procurement')], max_length=10)),
                ('category', models.CharField(help_text='e.g. Stationary Combustion, Grid Purchased Electricity, Business Travel', max_length=100)),
                ('activity_type', models.CharField(help_text='e.g. Diesel, Grid Electricity, Air Flight, Hotel Stay', max_length=100)),
                ('raw_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_value_tco2e', models.DecimalField(decimal_places=6, help_text='Emissions in tonnes of CO2 equivalent (tCO2e)', max_digits=18)),
                ('confidence_score', models.IntegerField(help_text='Data quality score from 0-100')),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('review', 'Needs Review'), ('error', 'Critical Error')], default='validated', max_length=20)),
                ('validation_notes', models.TextField(blank=True, help_text='Reasons for review flags or anomalies', null=True)),
                ('transaction_date', models.DateField(help_text='Occurred date or transaction date')),
                ('billing_start_date', models.DateField(blank=True, help_text='Start of billing cycle (Scope 2)', null=True)),
                ('billing_end_date', models.DateField(blank=True, help_text='End of billing cycle (Scope 2)', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True if approved/locked for audit. Cannot be edited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.uploadbatch')),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.rawingesteddata')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-transaction_date', 'facility'],
            },
        ),
        migrations.CreateModel(
            name='FacilityLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="e.g. SAP WERKS plant code '1000' or Utility Meter ID 'MTR-992'", max_length=100)),
                ('facility_name', models.CharField(help_text="e.g. 'Plant A' or 'Office C'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_lookups', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
