# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilitylookup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facilitylookup',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='normalizedrecord',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='normalizedrecord',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='normalizedrecord',
            name='tenant',
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'UK Grid Electricity 2024'", max_length=255)),
                ('source', models.CharField(help_text="Authoritative source, e.g. 'DEFRA 2024', 'EPA eGRID 2023', 'IPCC AR6'", max_length=255)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Indirect (Energy)'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('activity', models.CharField(help_text="Activity category, e.g. 'Stationary Combustion – Natural Gas'", max_length=150)),
                ('unit_from', models.CharField(help_text="Input unit the factor converts from, e.g. 'kWh', 'litres', 'km'", max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=10, help_text='kg CO2e per unit_from', max_digits=20)),
                ('valid_from', models.PositiveSmallIntegerField(help_text='Reporting year this factor first applies to, e.g. 2024')),
                ('valid_to', models.PositiveSmallIntegerField(blank=True, help_text='Last reporting year this factor applies to; null = still current', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'esg_emission_factor',
                'indexes': [models.Index(fields=['scope', 'activity', 'valid_from'], name='idx_factor_scope_act_year')],
            },
        ),
        migrations.CreateModel(
            name='FacilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="System-of-record code, e.g. SAP plant '1000' or meter ID 'MTR-992'", max_length=100)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Bangalore Plant A'", max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_profiles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'esg_facility_profile',
            },
        ),
        migrations.CreateModel(
            name='NormalisedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_year', models.PositiveSmallIntegerField()),
                ('facility_label', models.CharField(blank=True, help_text='Raw facility label from source, kept for traceability even when FK is resolved', max_length=255)),
                ('period_start', models.DateField(help_text='Start of the activity period (billing cycle start, trip departure date, etc.)')),
                ('period_end', models.DateField(help_text='End of the activity period; equal to period_start for point-in-time records')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP (Fuel & Procurement)'), ('UTILITY', 'Utility (Electricity Bills)'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Indirect (Energy)'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('category', models.CharField(blank=True, help_text="GHG Protocol category, e.g. 'Stationary Combustion', 'Business Travel — Air'", max_length=150)),
                ('activity_type', models.CharField(blank=True, help_text="Specific activity, e.g. 'Diesel', 'Grid Electricity', 'Short-Haul Flight'", max_length=150)),
                ('quantity_raw', models.DecimalField(decimal_places=6, help_text='Quantity as parsed from the source before unit conversion', max_digits=20)),
                ('unit_raw', models.CharField(help_text="Unit as received from source, e.g. 'gallons', 'kBTU', 'miles'", max_length=50)),
                ('quantity_normalised', models.DecimalField(decimal_places=6, help_text='Quantity after conversion to unit_normalised', max_digits=20)),
                ('unit_normalised', models.CharField(choices=[('kg_CO2e', 'Kilograms CO₂-equivalent'), ('tCO2e', 'Metric Tonnes CO₂-equivalent'), ('kWh', 'Kilowatt-hours'), ('MJ', 'Megajoules'), ('L', 'Litres'), ('km', 'Kilometres')], max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=8, help_text='Conversion factor applied, e.g. kg CO2e / kWh', max_digits=20)),
                ('emission_factor_source', models.CharField(blank=True, help_text="Textual citation, e.g. 'DEFRA 2024 Table 1A' (used when FK unavailable)", max_length=255)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Final GHG impact in kg CO2e — universal aggregation unit', max_digits=20)),
                ('confidence_score', models.SmallIntegerField(default=100, help_text='0–100. Calculated by the pipeline based on data completeness and source reliability. Records below the AUTO_APPROVED threshold (≥80) are routed to NEEDS_REVIEW.')),
                ('anomaly_flag', models.BooleanField(default=False, help_text='True when the pipeline detects a statistical outlier')),
                ('anomaly_reason', models.TextField(blank=True, help_text='Human-readable explanation of why the record was flagged')),
                ('review_status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('AUTO_APPROVED', 'Auto-Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked (Audited)')], default='NEEDS_REVIEW', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.uploadbatch')),
                ('emission_factor_ref', models.ForeignKey(blank=True, help_text='FK to the versioned factor row used for this calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_records', to='emissions.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, help_text='Resolved facility profile (null if unresolved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='emissions.facilityprofile')),
            ],
            options={
                'db_table': 'esg_emission_record',
            },
        ),
    ]
