# Generated by Django 6.0.5 on 2026-05-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_facilitylookup_unique_together_and_more'),
        ('ingestion', '0002_rawingestedrow_remove_rawingesteddata_batch_and_more'),
        ('reviews', '0002_auditentry_reviewcomment_remove_audittrail_record_and_more'),
        ('tenants', '0002_tenant_active_reporting_year_tenant_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='normalisedemissionrecord',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalisedemissionrecord',
            name='raw_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.rawingestedrow'),
        ),
        migrations.AddField(
            model_name='normalisedemissionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalisedemissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='tenants.tenant'),
        ),
        migrations.DeleteModel(
            name='FacilityLookup',
        ),
        migrations.DeleteModel(
            name='NormalizedRecord',
        ),
        migrations.AddIndex(
            model_name='facilityprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_facility_tenant_active'),
        ),
        migrations.AlterUniqueTogether(
            name='facilityprofile',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='normalisedemissionrecord',
            index=models.Index(fields=['tenant', 'reporting_year', 'scope'], name='idx_er_tenant_year_scope'),
        ),
        migrations.AddIndex(
            model_name='normalisedemissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='idx_er_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='normalisedemissionrecord',
            index=models.Index(fields=['tenant', 'source_type', 'reporting_year'], name='idx_er_tenant_src_year'),
        ),
        migrations.AddIndex(
            model_name='normalisedemissionrecord',
            index=models.Index(fields=['anomaly_flag'], name='idx_er_anomaly'),
        ),
        migrations.AddIndex(
            model_name='normalisedemissionrecord',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_er_period'),
        ),
        migrations.AddConstraint(
            model_name='normalisedemissionrecord',
            constraint=models.UniqueConstraint(fields=('raw_row', 'scope'), name='uq_emission_raw_row_scope'),
        ),
        migrations.AddConstraint(
            model_name='normalisedemissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='chk_period_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='normalisedemissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='chk_confidence_score_range'),
        ),
        migrations.AddConstraint(
            model_name='normalisedemissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('co2e_kg__gte', 0)), name='chk_co2e_non_negative'),
        ),
    ]
