# Generated by Django 6.0.5 on 2026-05-29 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_normalisedemissionrecord_locked_by_and_more'),
        ('ingestion', '0003_uploadbatch_uploaded_by_and_more'),
        ('tenants', '0002_tenant_active_reporting_year_tenant_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='normalisedemissionrecord',
            name='uq_emission_raw_row_scope',
        ),
        migrations.AlterField(
            model_name='normalisedemissionrecord',
            name='unit_normalised',
            field=models.CharField(choices=[('kg_CO2e', 'Kilograms CO₂-equivalent'), ('tCO2e', 'Metric Tonnes CO₂-equivalent'), ('kWh', 'Kilowatt-hours'), ('MJ', 'Megajoules'), ('L', 'Litres'), ('km', 'Kilometres'), ('kg', 'Kilograms'), ('night', 'Room-nights'), ('mile', 'Miles')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='normalisedemissionrecord',
            constraint=models.UniqueConstraint(fields=('raw_row', 'scope', 'period_start'), name='uq_emission_raw_row_scope_period'),
        ),
    ]
